# bootstrap.ps1 - native Windows bootstrap for the chezmoi + mise dotfiles.
#
# Usage:
#   powershell -ExecutionPolicy Bypass -File .\bootstrap.ps1
#   pwsh -NoProfile -ExecutionPolicy Bypass -File .\bootstrap.ps1

[CmdletBinding()]
param(
    [string]$DotfilesDir = (Join-Path $HOME '.dotfiles'),
    [string]$DotfilesRepoUrl = 'https://github.com/chugiau/dotfiles.git',
    [switch]$SkipApply
)

$ErrorActionPreference = 'Stop'

function Write-Info {
    param([string]$Message)
    Write-Host "[info]  $Message" -ForegroundColor Blue
}

function Write-Ok {
    param([string]$Message)
    Write-Host "[ok]    $Message" -ForegroundColor Green
}

function Write-Warn {
    param([string]$Message)
    Write-Host "[warn]  $Message" -ForegroundColor Yellow
}

function Die {
    param([string]$Message)
    Write-Error "[error] $Message"
    exit 1
}

function Test-Command {
    param([string]$Name)
    $null -ne (Get-Command $Name -ErrorAction SilentlyContinue)
}

function Update-ProcessPath {
    $machinePath = [Environment]::GetEnvironmentVariable('Path', 'Machine')
    $userPath = [Environment]::GetEnvironmentVariable('Path', 'User')
    $localBin = Join-Path $HOME '.local\bin'
    $miseShims = @((Join-Path $HOME '.local\share\mise\shims'))
    if ($env:LOCALAPPDATA) {
        $miseShims += (Join-Path $env:LOCALAPPDATA 'mise\shims')
    }

    $entries = @($machinePath, $userPath, $localBin) + $miseShims
    $env:Path = ($entries | Where-Object { $_ } | Select-Object -Unique) -join ';'
}

function Install-WithWinget {
    param(
        [Parameter(Mandatory = $true)][string]$Id,
        [Parameter(Mandatory = $true)][string]$Command,
        [Parameter(Mandatory = $true)][string]$Name
    )

    if (Test-Command $Command) {
        Write-Ok "$Name already installed"
        return
    }

    if (-not (Test-Command winget)) {
        Die "winget is not available. Install App Installer from Microsoft Store, then re-run bootstrap.ps1."
    }

    Write-Info "Installing $Name via winget ($Id)"
    winget install --id $Id --exact --source winget --accept-package-agreements --accept-source-agreements
    Update-ProcessPath

    if (Test-Command $Command) {
        Write-Ok "$Name installed"
    } else {
        Write-Warn "$Name was requested through winget, but '$Command' is not on PATH yet. Open a new terminal if the next step cannot find it."
    }
}

function Write-ChezmoiConfig {
    $configDir = Join-Path $HOME '.config\chezmoi'
    $configFile = Join-Path $configDir 'chezmoi.toml'
    New-Item -ItemType Directory -Force -Path $configDir | Out-Null

    $literalPath = $DotfilesDir -replace "'", "''"
    @"
# Generated by $DotfilesDir\bootstrap.ps1 - do not edit by hand.
sourceDir = '$literalPath'
"@ | Set-Content -LiteralPath $configFile -Encoding UTF8

    Write-Ok "Wrote chezmoi config: $configFile"
}

Write-Info 'Dotfiles Windows bootstrap starting...'
Update-ProcessPath

Install-WithWinget -Id Git.Git -Command git -Name Git
Install-WithWinget -Id twpayne.chezmoi -Command chezmoi -Name chezmoi
Install-WithWinget -Id jdx.mise -Command mise -Name mise

if (Test-Path -LiteralPath (Join-Path $DotfilesDir '.git')) {
    Write-Ok "Dotfiles repo already at $DotfilesDir"
} else {
    if (-not (Test-Command git)) {
        Die "git is not available after installation attempt"
    }
    Write-Info "Cloning $DotfilesRepoUrl -> $DotfilesDir"
    git clone $DotfilesRepoUrl $DotfilesDir
}

Write-ChezmoiConfig

if (-not $SkipApply) {
    if (-not (Test-Command chezmoi)) {
        Die "chezmoi is not available after installation attempt"
    }
    Write-Info 'Running chezmoi apply...'
    chezmoi apply
    Write-Ok 'chezmoi apply finished'
}

Write-Ok 'Bootstrap complete.'
Write-Info 'Open a new PowerShell session to pick up profile, mise shims, and tool paths.'
