---
- name: "core | Debian | Install core system packages"
  ansible.builtin.apt:
    name:
      - git
      - git-lfs
      - jq
      - openssh-client
      - gnupg
      - curl
      - wget
      - unzip
    state: present
    update_cache: true
  become: true
