---
- name: "homebrew | Debian | Install Homebrew prerequisites"
  ansible.builtin.apt:
    name:
      - build-essential
      - procps
      - curl
      - file
      - git
    state: present
    update_cache: true
  become: true
