---
- name: "pre | Determine Homebrew prefix path"
  ansible.builtin.set_fact:
    brew_prefix: >-
      {{ '/opt/homebrew' if ansible_system == 'Darwin' and ansible_architecture == 'arm64'
         else '/usr/local' if ansible_system == 'Darwin'
         else '/home/linuxbrew/.linuxbrew' }}

- name: "pre | Check Homebrew installed"
  ansible.builtin.stat:
    path: "{{ brew_prefix }}/bin/brew"
  register: brew_stat

- name: "pre | Set brew_available fact"
  ansible.builtin.set_fact:
    brew_available: "{{ brew_stat.stat.exists }}"

- name: "pre | Set brew_bin fact"
  ansible.builtin.set_fact:
    brew_bin: "{{ brew_prefix }}/bin/brew"
  when: brew_available | bool
