---
- name: "pre | Create XDG base directories"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ ansible_facts.env.HOME }}/.config"
    - "{{ ansible_facts.env.HOME }}/.local/share"
    - "{{ ansible_facts.env.HOME }}/.local/state"
    - "{{ ansible_facts.env.HOME }}/.local/bin"
    - "{{ ansible_facts.env.HOME }}/.cache"
