---
- name: "cli_tools | Archlinux | Install CLI tools"
  community.general.pacman:
    name:
      - bat
      - eza
      - lazygit
      - glow
    state: present
    update_cache: true
  become: true
